### PR TITLE
Sarah update galv cvrp

### PR DESCRIPTION
**Pull request by sarahwalker10**
- 2 new files in the notebook folder: create_full_service_df.ipynb and create_truck_only_df.ipynb (described in the README)

### CODE REVIEW

**Comment by sarahwalker10** [comment]
- 2 new scripts in the code folder: one_week_routes.py and cvrp_optimize_routes.py (descibed in the README)
- 5 new data files: distance_matrix_new.npy (downloaded from Yifan when she made the distance matrix), truck_ditances.csv, truck_service_locations.csv, full_service_locations.csv, indoor_outdoor_dist_matrix.csv (described in README)

**Comment by sarahwalker10** [comment]
Updated all of the READMEs and passed pre-checks

**Comment by rahimrasool** [comment]
Yet to be graded!

**Comment by rahimrasool** [comment]
Resolve the conflict please and submit

**Comment by rahimrasool** [comment]
Graded!

**Pull request merged**
